### PR TITLE
microk8s setup script and README update

### PR DESCRIPTION
**Pull request by akanarsky**
Fusion 5 Setup in MicroK8s

### CODE REVIEW

**Comment by mllu** [comment]
curious if we considering to use `kind` to provision local cluster https://kubernetes.io/docs/setup/learning-environment/kind/, I tried it and able to create a local cluster with fusion installed with one minor issue: there is no load balancer for local k8s cluster https://github.com/kubernetes-sigs/kind/issues/702. I guess for local k8s cluster running on MAC, ppl might be able to just use `kubectl port-forward svc/proxy 6764:6764` to access admin page?

**Comment by nddipiazza** [comment]
i tried it. Fails here:

Error: unable to build kubernetes objects from release manifest: unable to recognize "": no matches for kind "StatefulSet" in version "apps/v1beta2"

**Comment by nddipiazza** [comment]
> i tried it. Fails here:
> 
> Error: unable to build kubernetes objects from release manifest: unable to recognize "": no matches for kind "StatefulSet" in version "apps/v1beta2"

Ian Thebridge  2 hours ago
@nicholas.dipiazza That should be fixed in the latest version of the chart, if you  set the version to 5.0.3-3 then this shouldn’t be an issue

**Comment by nddipiazza** [comment]
2 issues I've found so far: 

1. The `f5-rpc-service` fails to start on microk8s. I tried scaling it from 0 back to 1 but it fails to start. It seems that the keep-alive kills it before it it is ready.
2. The parallel bulk loader job does not work. It will create a container, but it will stick in pending.

```
mk describe pod driver-lab4-load-from-gcs-3f0129f86a
Name:         driver-lab4-load-from-gcs-3f0129f86a
Namespace:    default
Priority:     0
Node:         <none>
Labels:       jobConfigId=lab4_load_from_GCS
              jobRunId=3f0129f86a
              spark-app-selector=spark-84bb5c7dde5f4e5f9b43634bd64d1c9c
              spark-role=driver
Annotations:  <none>
Status:       Pending
IP:           
IPs:          <none>
Containers:
  spark-kubernetes-driver:
    Image:       lucidworks/fusion-spark:5.0.2
    Ports:       7078/TCP, 7079/TCP, 4040/TCP
    Host Ports:  0/TCP, 0/TCP, 0/TCP
    Args:
      driver
      --properties-file
      /opt/spark/conf/spark.properties
      --class
      com.lucidworks.dc.SparkJobApplication
      spark-internal
      --spring.cloud.zookeeper.connect-string=f5-zookeeper
      --spring.cloud.zookeeper.discovery.enabled=false
      --ribbon.zookeeper.enabled=false
      --spring.cloud.kubernetes.enabled=true
      --spring.cloud.kubernetes.ribbon.enabled=true
      --spring.cloud.kubernetes.secrets.enabled=true
      --spring.profiles.active=kubernetes,jwt,fusion
      --spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://proxy:6764/oauth2/jwk
      --spring.security.oauth2.resourceserver.jwt.issuer-uri=http://proxy:6764/oauth2/default
      --curator.namespace=lwfusion/5.0
      --jobConfig={"type":"parallel-bulk-loader","id":"lab4_load_from_GCS","format":"parquet","path":"gs://solr-perf-data/test7m","outputCollection":"lab4","outputPartitions":18,"clearDatasource":false,"defineFieldsUsingInputSchema":true,"atomicUpdates":false,"transformScala":"def transform(inputDF: Dataset[Row]) : Dataset[Row] = {\n  inputDF.sample(0.05d)\n}","sparkConfig":[{"key":"spark.kubernetes.executor.request.cores","value":"1"},{"key":"spark.executor.cores","value":"6"},{"key":"spark.executor.instances","value":"3"},{"key":"spark.kubernetes.node.selector.fusion_node_type","value":"spark_only"}],"cacheAfterRead":false,"optimizeOutput":4,"continueAfterFailure":false,"type":"parallel-bulk-loader","collection":"lab4"}
      --jobRunId=3f0129f86a
      --solrZkHost=f5-zookeeper
    Limits:
      memory:  3456Mi
    Requests:
      cpu:     1
      memory:  3456Mi
    Environment:
      SPARK_DRIVER_BIND_ADDRESS:   (v1:status.podIP)
      SPARK_LOCAL_DIRS:           /var/data/spark-15c3accc-a9cc-478c-9591-47bd7eb90ef5
      service-account-key:        <set to the key 'sa' in secret 'service-account-key'>  Optional: false
      SPARK_CONF_DIR:             /opt/spark/conf
    Mounts:
      /etc/secrets from service-account-key-volume (rw)
      /opt/spark/conf from spark-conf-volume (rw)
      /var/data/spark-15c3accc-a9cc-478c-9591-47bd7eb90ef5 from spark-local-dir-1 (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from f5-job-launcher-spark-token-vgtp6 (ro)
Conditions:
  Type           Status
  PodScheduled   False 
Volumes:
  spark-local-dir-1:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:     
    SizeLimit:  <unset>
  service-account-key-volume:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  service-account-key
    Optional:    false
  spark-conf-volume:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      lab4loadfromgcs-3f0129f86a-1582244094301-driver-conf-map
    Optional:  false
  f5-job-launcher-spark-token-vgtp6:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  f5-job-launcher-spark-token-vgtp6
    Optional:    false
QoS Class:       Burstable
Node-Selectors:  fusion_node_type=spark_only
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason            Age        From               Message
  ----     ------            ----       ----               -------
  Warning  FailedScheduling  <unknown>  default-scheduler  0/1 nodes are available: 1 node(s) didn't match node selector.
  Warning  FailedScheduling  <unknown>  default-scheduler  0/1 nodes are available: 1 node(s) didn't match node selector.
```

**Comment by ian-thebridge-lucidworks** [comment]
@nddipiazza for the second issue, you have created the pbl job with a node selector of `fusion_node_type=spark_only` but you have no nodes in the cluster that have that label. If you re-run the job without that node selector it should schedule properly.

**Comment by akanarsky** [comment]
@nddipiazza @ian-thebridge-lucidworks  I am closing this one since I don't think it's relevant anymore.

**Pull request closed without merging**
